<?php
return  [
    'naruto' => [
        'name' => 'Naruto Uzumaki',
        'full-name' => 'Naruto Uzumaki',
        'status' => 'Alive',
        'birth' => 'October 10',
        'race' => 'Human',
        'gender' => 'Male',
        'age' => '33',
        'height' => '182 cm',
        'hair' => 'Blonde',
        'summary' => 'Naruto Uzumaki is the main character in the "Naruto" anime and manga series...',
        'abilities' => ['Rasengan', 'Sage Mode', 'Kyuubi Chakra'],
        'biography' => 'Naruto was born to Minato Namikaze and Kushina Uzumaki...',
        'image' => 'naruto.jpg',
        'gallery' => ['naruto1.jpg', 'naruto2.jpg', 'naruto3.jpg'],
    ],
    'sasuke' => [
        'name' => 'Sasuke Uchiha',
        'full-name' => 'Sasuke Uchiha',
        'status' => 'Alive',
        'birth' => 'July 23',
        'race' => 'Human',
        'gender' => 'Male',
        'age' => '33',
        'height' => '183 cm',
        'hair' => 'Black',
        'summary' => 'Sasuke Uchiha is one of the last surviving members of Konohagakure\'s Uchiha clan...',
        'abilities' => ['Sharingan', 'Chidori', 'Susanoo'],
        'biography' => 'Sasuke was born into the Uchiha clan as the younger son of Fugaku and Mikoto Uchiha...',
        'image' => 'sasuke.jpg',
        'gallery' => ['sasuke1.jpg', 'sasuke2.jpg', 'sasuke3.jpg'],
    ],
    'gandalf' => [
        'name' => 'Gandalf',
        'full-name' => 'Gandalf the Grey/White',
        'status' => 'Alive',
        'birth' => 'Unknown',
        'race' => 'Maia',
        'gender' => 'Male',
        'age' => '24 000',
        'height' => '168 cm',
        'hair' => 'Grey/White',
        'summary' => 'Gandalf is a powerful wizard from J.R.R. Tolkien\'s "The Lord of the Rings"...',
        'abilities' => ['Magic', 'Wisdom', 'Leadership'],
        'biography' => 'Gandalf is one of the Istari, wizards sent to help Middle-earth against Sauron...',
        'image' => 'gandalf.webp',
        'gallery' => ['gandalf1.jpg', 'gandalf2.jpg', 'gandalf3.jpg'],
    ],
    'ironman' => [
        'name' => 'Iron Man (Tony Stark)',
        'full-name' => 'Tony Stark',
        'status' => 'Deceased',
        'birth' => 'May 29, 1970',
        'race' => 'Human',
        'gender' => 'Male',
        'age' => 'Male',
        'height' => '175 cm',
        'hair' => 'Black',
        'summary' => 'Iron Man is a superhero from the Marvel Universe, also known as Tony Stark...',
        'abilities' => ['Powered Armor Suit', 'Genius-Level Intellect', 'Repulsor Rays'],
        'biography' => 'Tony Stark is a billionaire industrialist and genius inventor who created the Iron Man armor...',
        'image' => 'ironman.jpg',
        'gallery' => ['ironman1.jpg', 'ironman2.jpg', 'ironman3.jpg'],
    ],
];
